### ISSUE TITLE
About training logs.

### ISSUE THREAD

**Issue by FingerRec** [sjenni/temporal-ssl#2]
Hi Jenni,
I'm the author of [VTDL](https://arxiv.org/abs/2008.02129).  I'm preparing my manuscript and aims to compare with your work. It seems your R(2+1)D model can achieve 46.4 with 112 resolution input which seems very surprising. Could you provide train logs or pretrain weight for your experiments?

**Comment by sjenni** [comment]
Hi,
I plan to release the R(2+1)D training code as well eventually. Currently, I am a bit busy, unfortunately :)
The 3D-ResNet model achieves similar or higher performance on 128x128 resolution and the setup is otherwise identical. Let me know if I should provide pre-trained weights for this model.
Cheers, 
Simon
